/*
 * (C) Copyright IBM Corp. 2020.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.networking.transit_gateway_apis.v1;

import com.google.gson.JsonObject;
import com.ibm.cloud.networking.common.SdkCommon;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DeleteTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DeleteTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DetailGatewayLocationOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DetailTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DetailTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListGatewayLocationsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListTransitGatewayConnectionsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListTransitGatewaysOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TSCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TSLocation;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGateway;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayConnectionCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayConnectionCust;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.UpdateTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.UpdateTransitGatewayOptions;
import com.ibm.cloud.sdk.core.http.RequestBuilder;
import com.ibm.cloud.sdk.core.http.ResponseConverter;
import com.ibm.cloud.sdk.core.http.ServiceCall;
import com.ibm.cloud.sdk.core.security.Authenticator;
import com.ibm.cloud.sdk.core.security.ConfigBasedAuthenticatorFactory;
import com.ibm.cloud.sdk.core.service.BaseService;
import com.ibm.cloud.sdk.core.util.ResponseConverterUtils;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Map;
import java.util.Map.Entry;

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator).
 *
 * @version v1
 */
public class TransitGatewayApis extends BaseService {

  public static final String DEFAULT_SERVICE_NAME = "transit_gateway_apis";

  public static final String DEFAULT_SERVICE_URL = "https://transit.cloud.ibm.com/v1";

  private Date version;
  private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

 /**
   * Class method which constructs an instance of the `TransitGatewayApis` client.
   * The default service name is used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @return an instance of the `TransitGatewayApis` client using external configuration
   */
  public static TransitGatewayApis newInstance(Date version) {
    return newInstance(version, DEFAULT_SERVICE_NAME);
  }

  /**
   * Class method which constructs an instance of the `TransitGatewayApis` client.
   * The specified service name is used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @param serviceName the service name to be used when configuring the client instance
   * @return an instance of the `TransitGatewayApis` client using external configuration
   */
  public static TransitGatewayApis newInstance(Date version, String serviceName) {
    Authenticator authenticator = ConfigBasedAuthenticatorFactory.getAuthenticator(serviceName);
    TransitGatewayApis service = new TransitGatewayApis(version, serviceName, authenticator);
    service.configureService(serviceName);
    return service;
  }

  /**
   * Constructs an instance of the `TransitGatewayApis` client.
   * The specified service name and authenticator are used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @param serviceName the service name to be used when configuring the client instance
   * @param authenticator the {@link Authenticator} instance to be configured for this client
   */
  public TransitGatewayApis(Date version, String serviceName, Authenticator authenticator) {
    super(serviceName, authenticator);
    setServiceUrl(DEFAULT_SERVICE_URL);
    setVersion(version);
  }

  /**
   * Gets the version.
   *
   * Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current date may be
   * provided. Specify the current date to request the latest version.
   *
   * @return the version
   */
  public Date getVersion() {
    return this.version;
  }

  /**
   * Sets the version.
   *
   * @param version the new version
   */
  public void setVersion(final Date version) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(version, "version cannot be null.");
    this.version = version;
  }

  /**
   * Retrieves all Transit Gateways.
   *
   * List all the Transit Gateways in the account. User will get a list of Transit Gateways they have access to 'view'.
   *
   * @param listTransitGatewaysOptions the {@link ListTransitGatewaysOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayCollection}
   */
  public ServiceCall<TransitGatewayCollection> listTransitGateways(ListTransitGatewaysOptions listTransitGatewaysOptions) {
    String[] pathSegments = { "transit_gateways" };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listTransitGateways");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (listTransitGatewaysOptions != null) {
      builder.query("version", dateFormat.format(this.version));
    }
    ResponseConverter<TransitGatewayCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all Transit Gateways.
   *
   * List all the Transit Gateways in the account. User will get a list of Transit Gateways they have access to 'view'.
   *
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayCollection}
   */
  public ServiceCall<TransitGatewayCollection> listTransitGateways() {
    return listTransitGateways(null);
  }

  /**
   * Creates a Transit Gateway.
   *
   * Create a Transit Gateway based on the supplied input template.
   *
   * @param createTransitGatewayOptions the {@link CreateTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> createTransitGateway(CreateTransitGatewayOptions createTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayOptions,
      "createTransitGatewayOptions cannot be null");
    String[] pathSegments = { "transit_gateways" };
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("location", createTransitGatewayOptions.location());
    contentJson.addProperty("name", createTransitGatewayOptions.name());
    if (createTransitGatewayOptions.global() != null) {
      contentJson.addProperty("global", createTransitGatewayOptions.global());
    }
    if (createTransitGatewayOptions.resourceGroup() != null) {
      contentJson.add("resource_group", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createTransitGatewayOptions.resourceGroup()));
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Deletes specified Transit Gateway.
   *
   * This request deletes a Transit Gateway. This operation cannot be reversed. For this request to succeed, the Transit
   * Gateway must not contain connections.
   *
   * @param deleteTransitGatewayOptions the {@link DeleteTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> deleteTransitGateway(DeleteTransitGatewayOptions deleteTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteTransitGatewayOptions,
      "deleteTransitGatewayOptions cannot be null");
    String[] pathSegments = { "transit_gateways" };
    String[] pathParameters = { deleteTransitGatewayOptions.id() };
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "deleteTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves specified Transit Gateway.
   *
   * This request retrieves a single Transit Gateway specified by the identifier in the URL.
   *
   * @param detailTransitGatewayOptions the {@link DetailTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> detailTransitGateway(DetailTransitGatewayOptions detailTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(detailTransitGatewayOptions,
      "detailTransitGatewayOptions cannot be null");
    String[] pathSegments = { "transit_gateways" };
    String[] pathParameters = { detailTransitGatewayOptions.id() };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "detailTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Updates specified Transit Gateway.
   *
   * This request updates a Transit Gateway's name and/or global flag.
   *
   * @param updateTransitGatewayOptions the {@link UpdateTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> updateTransitGateway(UpdateTransitGatewayOptions updateTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(updateTransitGatewayOptions,
      "updateTransitGatewayOptions cannot be null");
    String[] pathSegments = { "transit_gateways" };
    String[] pathParameters = { updateTransitGatewayOptions.id() };
    RequestBuilder builder = RequestBuilder.patch(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "updateTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    final JsonObject contentJson = new JsonObject();
    if (updateTransitGatewayOptions.global() != null) {
      contentJson.addProperty("global", updateTransitGatewayOptions.global());
    }
    if (updateTransitGatewayOptions.name() != null) {
      contentJson.addProperty("name", updateTransitGatewayOptions.name());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all connections in a Transit Gateway.
   *
   * This request retrieves all connections in a Transit Gateway.
   *
   * @param listTransitGatewayConnectionsOptions the {@link ListTransitGatewayConnectionsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCollection}
   */
  public ServiceCall<TransitGatewayConnectionCollection> listTransitGatewayConnections(ListTransitGatewayConnectionsOptions listTransitGatewayConnectionsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(listTransitGatewayConnectionsOptions,
      "listTransitGatewayConnectionsOptions cannot be null");
    String[] pathSegments = { "transit_gateways", "connections" };
    String[] pathParameters = { listTransitGatewayConnectionsOptions.transitGatewayId() };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listTransitGatewayConnections");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<TransitGatewayConnectionCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Add connection to a Transit Gateway.
   *
   * Add a connection to Transit Gateway.
   *
   * @param createTransitGatewayConnectionOptions the {@link CreateTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> createTransitGatewayConnection(CreateTransitGatewayConnectionOptions createTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayConnectionOptions,
      "createTransitGatewayConnectionOptions cannot be null");
    String[] pathSegments = { "transit_gateways", "connections" };
    String[] pathParameters = { createTransitGatewayConnectionOptions.transitGatewayId() };
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("network_type", createTransitGatewayConnectionOptions.networkType());
    if (createTransitGatewayConnectionOptions.name() != null) {
      contentJson.addProperty("name", createTransitGatewayConnectionOptions.name());
    }
    if (createTransitGatewayConnectionOptions.networkId() != null) {
      contentJson.addProperty("network_id", createTransitGatewayConnectionOptions.networkId());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Remove connection from Transit Gateway.
   *
   * After the specified connection is detached, entities still within the Transit Gateway will no longer be able to
   * communicate directly to it through the IBM Cloud private backbone.
   *
   * @param deleteTransitGatewayConnectionOptions the {@link DeleteTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> deleteTransitGatewayConnection(DeleteTransitGatewayConnectionOptions deleteTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteTransitGatewayConnectionOptions,
      "deleteTransitGatewayConnectionOptions cannot be null");
    String[] pathSegments = { "transit_gateways", "connections" };
    String[] pathParameters = { deleteTransitGatewayConnectionOptions.transitGatewayId(), deleteTransitGatewayConnectionOptions.id() };
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "deleteTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves specified Transit Gateway connection.
   *
   * This request retrieves a connection from the Transit Gateway.
   *
   * @param detailTransitGatewayConnectionOptions the {@link DetailTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> detailTransitGatewayConnection(DetailTransitGatewayConnectionOptions detailTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(detailTransitGatewayConnectionOptions,
      "detailTransitGatewayConnectionOptions cannot be null");
    String[] pathSegments = { "transit_gateways", "connections" };
    String[] pathParameters = { detailTransitGatewayConnectionOptions.transitGatewayId(), detailTransitGatewayConnectionOptions.id() };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "detailTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Updates specified Transit Gateway connection.
   *
   * Update the name of a connection to a Transit Gateway.
   *
   * @param updateTransitGatewayConnectionOptions the {@link UpdateTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> updateTransitGatewayConnection(UpdateTransitGatewayConnectionOptions updateTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(updateTransitGatewayConnectionOptions,
      "updateTransitGatewayConnectionOptions cannot be null");
    String[] pathSegments = { "transit_gateways", "connections" };
    String[] pathParameters = { updateTransitGatewayConnectionOptions.transitGatewayId(), updateTransitGatewayConnectionOptions.id() };
    RequestBuilder builder = RequestBuilder.patch(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "updateTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    final JsonObject contentJson = new JsonObject();
    if (updateTransitGatewayConnectionOptions.name() != null) {
      contentJson.addProperty("name", updateTransitGatewayConnectionOptions.name());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List all locations that support Transit Gateways.
   *
   * List all locations that support Transit Gateways.
   *
   * @param listGatewayLocationsOptions the {@link ListGatewayLocationsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TSCollection}
   */
  public ServiceCall<TSCollection> listGatewayLocations(ListGatewayLocationsOptions listGatewayLocationsOptions) {
    String[] pathSegments = { "locations" };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listGatewayLocations");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (listGatewayLocationsOptions != null) {
      builder.query("version", dateFormat.format(this.version));
    }
    ResponseConverter<TSCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TSCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List all locations that support Transit Gateways.
   *
   * List all locations that support Transit Gateways.
   *
   * @return a {@link ServiceCall} with a result of type {@link TSCollection}
   */
  public ServiceCall<TSCollection> listGatewayLocations() {
    return listGatewayLocations(null);
  }

  /**
   * Show the details of a given Transit Gateway location.
   *
   * Get the details of a Transit Gateway Location.
   *
   * @param detailGatewayLocationOptions the {@link DetailGatewayLocationOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TSLocation}
   */
  public ServiceCall<TSLocation> detailGatewayLocation(DetailGatewayLocationOptions detailGatewayLocationOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(detailGatewayLocationOptions,
      "detailGatewayLocationOptions cannot be null");
    String[] pathSegments = { "locations" };
    String[] pathParameters = { detailGatewayLocationOptions.name() };
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.constructHttpUrl(getServiceUrl(), pathSegments, pathParameters));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "detailGatewayLocation");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", dateFormat.format(this.version));
    ResponseConverter<TSLocation> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TSLocation>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

}
