/*
 * (C) Copyright IBM Corp. 2021.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

/*
 * IBM OpenAPI SDK Code Generator Version: 3.41.1-790c0dfc-20211021-231519
 */

package com.ibm.cloud.networking.transit_gateway_apis.v1;

import com.google.gson.JsonObject;
import com.ibm.cloud.networking.common.SdkCommon;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayConnectionActionsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.CreateTransitGatewayRouteReportOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DeleteTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DeleteTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.DeleteTransitGatewayRouteReportOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.GetGatewayLocationOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.GetTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.GetTransitGatewayOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.GetTransitGatewayRouteReportOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListConnectionsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListGatewayLocationsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListTransitGatewayConnectionsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListTransitGatewayRouteReportsOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.ListTransitGatewaysOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.RouteReport;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.RouteReportCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TSCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TSLocation;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitConnectionCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGateway;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayConnectionCollection;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.TransitGatewayConnectionCust;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.UpdateTransitGatewayConnectionOptions;
import com.ibm.cloud.networking.transit_gateway_apis.v1.model.UpdateTransitGatewayOptions;
import com.ibm.cloud.sdk.core.http.RequestBuilder;
import com.ibm.cloud.sdk.core.http.ResponseConverter;
import com.ibm.cloud.sdk.core.http.ServiceCall;
import com.ibm.cloud.sdk.core.security.Authenticator;
import com.ibm.cloud.sdk.core.security.ConfigBasedAuthenticatorFactory;
import com.ibm.cloud.sdk.core.service.BaseService;
import com.ibm.cloud.sdk.core.util.ResponseConverterUtils;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator).
 *
 * API Version: __VERSION__
 */
public class TransitGatewayApis extends BaseService {

  public static final String DEFAULT_SERVICE_NAME = "transit_gateway_apis";

  public static final String DEFAULT_SERVICE_URL = "https://transit.cloud.ibm.com/v1";

  private String version;

 /**
   * Class method which constructs an instance of the `TransitGatewayApis` client.
   * The default service name is used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @return an instance of the `TransitGatewayApis` client using external configuration
   */
  public static TransitGatewayApis newInstance(String version) {
    return newInstance(version, DEFAULT_SERVICE_NAME);
  }

  /**
   * Class method which constructs an instance of the `TransitGatewayApis` client.
   * The specified service name is used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @param serviceName the service name to be used when configuring the client instance
   * @return an instance of the `TransitGatewayApis` client using external configuration
   */
  public static TransitGatewayApis newInstance(String version, String serviceName) {
    Authenticator authenticator = ConfigBasedAuthenticatorFactory.getAuthenticator(serviceName);
    TransitGatewayApis service = new TransitGatewayApis(version, serviceName, authenticator);
    service.configureService(serviceName);
    return service;
  }

  /**
   * Constructs an instance of the `TransitGatewayApis` client.
   * The specified service name and authenticator are used to configure the client instance.
   *
   * @param version Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current
 * date may be provided. Specify the current date to request the latest version.
   * @param serviceName the service name to be used when configuring the client instance
   * @param authenticator the {@link Authenticator} instance to be configured for this client
   */
  public TransitGatewayApis(String version, String serviceName, Authenticator authenticator) {
    super(serviceName, authenticator);
    setServiceUrl(DEFAULT_SERVICE_URL);
    setVersion(version);
  }

  /**
   * Gets the version.
   *
   * Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current date may be
   * provided. Specify the current date to request the latest version.
   *
   * @return the version
   */
  public String getVersion() {
    return this.version;
  }

  /**
   * Sets the version.
   *
   * @param version the new version
   */
  public void setVersion(final String version) {
    com.ibm.cloud.sdk.core.util.Validator.notEmpty(version, "version cannot be empty.");
    this.version = version;
  }

  /**
   * Retrieves all connections.
   *
   * List all transit gateway connections associated with this account.
   *
   * @param listConnectionsOptions the {@link ListConnectionsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitConnectionCollection}
   */
  public ServiceCall<TransitConnectionCollection> listConnections(ListConnectionsOptions listConnectionsOptions) {
    if (listConnectionsOptions == null) {
      listConnectionsOptions = new ListConnectionsOptions.Builder().build();
    }
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/connections"));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listConnections");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    if (listConnectionsOptions.limit() != null) {
      builder.query("limit", String.valueOf(listConnectionsOptions.limit()));
    }
    if (listConnectionsOptions.start() != null) {
      builder.query("start", String.valueOf(listConnectionsOptions.start()));
    }
    if (listConnectionsOptions.networkId() != null) {
      builder.query("network_id", String.valueOf(listConnectionsOptions.networkId()));
    }
    ResponseConverter<TransitConnectionCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitConnectionCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all connections.
   *
   * List all transit gateway connections associated with this account.
   *
   * @return a {@link ServiceCall} with a result of type {@link TransitConnectionCollection}
   */
  public ServiceCall<TransitConnectionCollection> listConnections() {
    return listConnections(null);
  }

  /**
   * List route reports.
   *
   * Retrieve all route reports for the specified Transit Gateway.  There will normally be at most one completed report
   * and one pending report.  Additionally, completed route reports are written to IBM Cloud Activity Tracker.
   *
   * @param listTransitGatewayRouteReportsOptions the {@link ListTransitGatewayRouteReportsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link RouteReportCollection}
   */
  public ServiceCall<RouteReportCollection> listTransitGatewayRouteReports(ListTransitGatewayRouteReportsOptions listTransitGatewayRouteReportsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(listTransitGatewayRouteReportsOptions,
      "listTransitGatewayRouteReportsOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", listTransitGatewayRouteReportsOptions.transitGatewayId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/route_reports", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listTransitGatewayRouteReports");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<RouteReportCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<RouteReportCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Request a route report.
   *
   * Request route report generation.  While report generation is in progress, additional requests to generate a report
   * are ignored and return the current pending report.
   *
   * @param createTransitGatewayRouteReportOptions the {@link CreateTransitGatewayRouteReportOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link RouteReport}
   */
  public ServiceCall<RouteReport> createTransitGatewayRouteReport(CreateTransitGatewayRouteReportOptions createTransitGatewayRouteReportOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayRouteReportOptions,
      "createTransitGatewayRouteReportOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", createTransitGatewayRouteReportOptions.transitGatewayId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/route_reports", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGatewayRouteReport");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<RouteReport> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<RouteReport>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Delete route report.
   *
   * Delete a route report.
   *
   * @param deleteTransitGatewayRouteReportOptions the {@link DeleteTransitGatewayRouteReportOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> deleteTransitGatewayRouteReport(DeleteTransitGatewayRouteReportOptions deleteTransitGatewayRouteReportOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteTransitGatewayRouteReportOptions,
      "deleteTransitGatewayRouteReportOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", deleteTransitGatewayRouteReportOptions.transitGatewayId());
    pathParamsMap.put("id", deleteTransitGatewayRouteReportOptions.id());
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/route_reports/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "deleteTransitGatewayRouteReport");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieve route report.
   *
   * Retrieve a route report.
   *
   * @param getTransitGatewayRouteReportOptions the {@link GetTransitGatewayRouteReportOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link RouteReport}
   */
  public ServiceCall<RouteReport> getTransitGatewayRouteReport(GetTransitGatewayRouteReportOptions getTransitGatewayRouteReportOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getTransitGatewayRouteReportOptions,
      "getTransitGatewayRouteReportOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", getTransitGatewayRouteReportOptions.transitGatewayId());
    pathParamsMap.put("id", getTransitGatewayRouteReportOptions.id());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/route_reports/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "getTransitGatewayRouteReport");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<RouteReport> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<RouteReport>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all Transit Gateways.
   *
   * List all Transit Gateways in account the caller is authorized to view.
   *
   * @param listTransitGatewaysOptions the {@link ListTransitGatewaysOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayCollection}
   */
  public ServiceCall<TransitGatewayCollection> listTransitGateways(ListTransitGatewaysOptions listTransitGatewaysOptions) {
    if (listTransitGatewaysOptions == null) {
      listTransitGatewaysOptions = new ListTransitGatewaysOptions.Builder().build();
    }
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways"));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listTransitGateways");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    if (listTransitGatewaysOptions.limit() != null) {
      builder.query("limit", String.valueOf(listTransitGatewaysOptions.limit()));
    }
    if (listTransitGatewaysOptions.start() != null) {
      builder.query("start", String.valueOf(listTransitGatewaysOptions.start()));
    }
    ResponseConverter<TransitGatewayCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all Transit Gateways.
   *
   * List all Transit Gateways in account the caller is authorized to view.
   *
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayCollection}
   */
  public ServiceCall<TransitGatewayCollection> listTransitGateways() {
    return listTransitGateways(null);
  }

  /**
   * Creates a Transit Gateway.
   *
   * Create a Transit Gateway based on the supplied input template.
   *
   * @param createTransitGatewayOptions the {@link CreateTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> createTransitGateway(CreateTransitGatewayOptions createTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayOptions,
      "createTransitGatewayOptions cannot be null");
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways"));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("location", createTransitGatewayOptions.location());
    contentJson.addProperty("name", createTransitGatewayOptions.name());
    if (createTransitGatewayOptions.global() != null) {
      contentJson.addProperty("global", createTransitGatewayOptions.global());
    }
    if (createTransitGatewayOptions.resourceGroup() != null) {
      contentJson.add("resource_group", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createTransitGatewayOptions.resourceGroup()));
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Deletes specified Transit Gateway.
   *
   * This request deletes a Transit Gateway. This operation cannot be reversed. For this request to succeed, the Transit
   * Gateway must not contain connections.
   *
   * @param deleteTransitGatewayOptions the {@link DeleteTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> deleteTransitGateway(DeleteTransitGatewayOptions deleteTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteTransitGatewayOptions,
      "deleteTransitGatewayOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("id", deleteTransitGatewayOptions.id());
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "deleteTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves specified Transit Gateway.
   *
   * This request retrieves a single Transit Gateway specified by the identifier in the URL.
   *
   * @param getTransitGatewayOptions the {@link GetTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> getTransitGateway(GetTransitGatewayOptions getTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getTransitGatewayOptions,
      "getTransitGatewayOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("id", getTransitGatewayOptions.id());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "getTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Updates specified Transit Gateway.
   *
   * This request updates a Transit Gateway's name and/or global flag.
   *
   * @param updateTransitGatewayOptions the {@link UpdateTransitGatewayOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGateway}
   */
  public ServiceCall<TransitGateway> updateTransitGateway(UpdateTransitGatewayOptions updateTransitGatewayOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(updateTransitGatewayOptions,
      "updateTransitGatewayOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("id", updateTransitGatewayOptions.id());
    RequestBuilder builder = RequestBuilder.patch(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "updateTransitGateway");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    final JsonObject contentJson = new JsonObject();
    if (updateTransitGatewayOptions.global() != null) {
      contentJson.addProperty("global", updateTransitGatewayOptions.global());
    }
    if (updateTransitGatewayOptions.name() != null) {
      contentJson.addProperty("name", updateTransitGatewayOptions.name());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGateway> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGateway>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves all connections in a Transit Gateway.
   *
   * This request retrieves all connections in a Transit Gateway.
   *
   * @param listTransitGatewayConnectionsOptions the {@link ListTransitGatewayConnectionsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCollection}
   */
  public ServiceCall<TransitGatewayConnectionCollection> listTransitGatewayConnections(ListTransitGatewayConnectionsOptions listTransitGatewayConnectionsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(listTransitGatewayConnectionsOptions,
      "listTransitGatewayConnectionsOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", listTransitGatewayConnectionsOptions.transitGatewayId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listTransitGatewayConnections");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<TransitGatewayConnectionCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Add connection to a Transit Gateway.
   *
   * Add a connection to Transit Gateway.
   *
   * @param createTransitGatewayConnectionOptions the {@link CreateTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> createTransitGatewayConnection(CreateTransitGatewayConnectionOptions createTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayConnectionOptions,
      "createTransitGatewayConnectionOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", createTransitGatewayConnectionOptions.transitGatewayId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("network_type", createTransitGatewayConnectionOptions.networkType());
    if (createTransitGatewayConnectionOptions.baseConnectionId() != null) {
      contentJson.addProperty("base_connection_id", createTransitGatewayConnectionOptions.baseConnectionId());
    }
    if (createTransitGatewayConnectionOptions.localGatewayIp() != null) {
      contentJson.addProperty("local_gateway_ip", createTransitGatewayConnectionOptions.localGatewayIp());
    }
    if (createTransitGatewayConnectionOptions.localTunnelIp() != null) {
      contentJson.addProperty("local_tunnel_ip", createTransitGatewayConnectionOptions.localTunnelIp());
    }
    if (createTransitGatewayConnectionOptions.name() != null) {
      contentJson.addProperty("name", createTransitGatewayConnectionOptions.name());
    }
    if (createTransitGatewayConnectionOptions.networkAccountId() != null) {
      contentJson.addProperty("network_account_id", createTransitGatewayConnectionOptions.networkAccountId());
    }
    if (createTransitGatewayConnectionOptions.networkId() != null) {
      contentJson.addProperty("network_id", createTransitGatewayConnectionOptions.networkId());
    }
    if (createTransitGatewayConnectionOptions.remoteBgpAsn() != null) {
      contentJson.addProperty("remote_bgp_asn", createTransitGatewayConnectionOptions.remoteBgpAsn());
    }
    if (createTransitGatewayConnectionOptions.remoteGatewayIp() != null) {
      contentJson.addProperty("remote_gateway_ip", createTransitGatewayConnectionOptions.remoteGatewayIp());
    }
    if (createTransitGatewayConnectionOptions.remoteTunnelIp() != null) {
      contentJson.addProperty("remote_tunnel_ip", createTransitGatewayConnectionOptions.remoteTunnelIp());
    }
    if (createTransitGatewayConnectionOptions.zone() != null) {
      contentJson.add("zone", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createTransitGatewayConnectionOptions.zone()));
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Remove connection from Transit Gateway.
   *
   * After the specified connection is detached, entities still within the Transit Gateway will no longer be able to
   * communicate directly to it through the IBM Cloud private backbone.
   *
   * @param deleteTransitGatewayConnectionOptions the {@link DeleteTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> deleteTransitGatewayConnection(DeleteTransitGatewayConnectionOptions deleteTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteTransitGatewayConnectionOptions,
      "deleteTransitGatewayConnectionOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", deleteTransitGatewayConnectionOptions.transitGatewayId());
    pathParamsMap.put("id", deleteTransitGatewayConnectionOptions.id());
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "deleteTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves specified Transit Gateway connection.
   *
   * This request retrieves a connection from the Transit Gateway.
   *
   * @param getTransitGatewayConnectionOptions the {@link GetTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> getTransitGatewayConnection(GetTransitGatewayConnectionOptions getTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getTransitGatewayConnectionOptions,
      "getTransitGatewayConnectionOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", getTransitGatewayConnectionOptions.transitGatewayId());
    pathParamsMap.put("id", getTransitGatewayConnectionOptions.id());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "getTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Updates specified Transit Gateway connection.
   *
   * Update the name of a connection to a Transit Gateway.
   *
   * @param updateTransitGatewayConnectionOptions the {@link UpdateTransitGatewayConnectionOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TransitGatewayConnectionCust}
   */
  public ServiceCall<TransitGatewayConnectionCust> updateTransitGatewayConnection(UpdateTransitGatewayConnectionOptions updateTransitGatewayConnectionOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(updateTransitGatewayConnectionOptions,
      "updateTransitGatewayConnectionOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", updateTransitGatewayConnectionOptions.transitGatewayId());
    pathParamsMap.put("id", updateTransitGatewayConnectionOptions.id());
    RequestBuilder builder = RequestBuilder.patch(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections/{id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "updateTransitGatewayConnection");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    final JsonObject contentJson = new JsonObject();
    if (updateTransitGatewayConnectionOptions.name() != null) {
      contentJson.addProperty("name", updateTransitGatewayConnectionOptions.name());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<TransitGatewayConnectionCust> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TransitGatewayConnectionCust>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Perform actions on a connection for a Transit Gateway.
   *
   * Allow a network owner to approve or reject a cross-account connection request.
   *
   * @param createTransitGatewayConnectionActionsOptions the {@link CreateTransitGatewayConnectionActionsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a void result
   */
  public ServiceCall<Void> createTransitGatewayConnectionActions(CreateTransitGatewayConnectionActionsOptions createTransitGatewayConnectionActionsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createTransitGatewayConnectionActionsOptions,
      "createTransitGatewayConnectionActionsOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("transit_gateway_id", createTransitGatewayConnectionActionsOptions.transitGatewayId());
    pathParamsMap.put("id", createTransitGatewayConnectionActionsOptions.id());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/transit_gateways/{transit_gateway_id}/connections/{id}/actions", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "createTransitGatewayConnectionActions");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.query("version", String.valueOf(this.version));
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("action", createTransitGatewayConnectionActionsOptions.action());
    builder.bodyJson(contentJson);
    ResponseConverter<Void> responseConverter = ResponseConverterUtils.getVoid();
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List all locations that support Transit Gateways.
   *
   * List all locations that support Transit Gateways.
   *
   * @param listGatewayLocationsOptions the {@link ListGatewayLocationsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TSCollection}
   */
  public ServiceCall<TSCollection> listGatewayLocations(ListGatewayLocationsOptions listGatewayLocationsOptions) {
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/locations"));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "listGatewayLocations");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<TSCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TSCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List all locations that support Transit Gateways.
   *
   * List all locations that support Transit Gateways.
   *
   * @return a {@link ServiceCall} with a result of type {@link TSCollection}
   */
  public ServiceCall<TSCollection> listGatewayLocations() {
    return listGatewayLocations(null);
  }

  /**
   * Show the details of a given Transit Gateway location.
   *
   * Get the details of a Transit Gateway Location.
   *
   * @param getGatewayLocationOptions the {@link GetGatewayLocationOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link TSLocation}
   */
  public ServiceCall<TSLocation> getGatewayLocation(GetGatewayLocationOptions getGatewayLocationOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getGatewayLocationOptions,
      "getGatewayLocationOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("name", getGatewayLocationOptions.name());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/locations/{name}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("transit_gateway_apis", "v1", "getGatewayLocation");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("version", String.valueOf(this.version));
    ResponseConverter<TSLocation> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<TSLocation>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

}
